name: qa
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
        - uses: golangci/golangci-lint-action@v5
          with:
            version: latest
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test -v ./...
      - name: Run race tests
        run: go test -v -race ./...
      - name: Start Testing DNS Server
        run: docker run -d -p 5353:53/udp -v ./coredns/coredns:/root/ coredns/coredns -conf /root/Corefile
      - name: Run integration tests
        run: go test -tags integration -v ./cmd
